### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/local/tmp/libnativeDump64.so" has unexpected e_machine: 40

### ISSUE THREAD

**Issue by hibikikkk** [WrBug/dumpDex#22]
环境：android studio 3.0
genymotion 8.0模拟器
develop分支编译出的apk
libnativeDump.so已复制并改权限
XposedInit.java已加包名

错误信息：
05-09 13:27:00.790  2319  2319 I Xposed  : dumpdex.PackerInfo-> find class:com.tencent.StubShell.TxAppEntry
05-09 13:27:00.790  2319  2319 I Xposed  : dumpdex.PackerInfo-> find packerType :腾讯加固
05-09 13:27:00.790  2319  2319 I Xposed  : dumpdex-> sdk version:26
05-09 13:27:00.792  2319  2319 E Xposed  : java.lang.UnsatisfiedLinkError: dlopen failed: "/data/local/tmp/libnativeDump64.so" has unexpected e_machine: 40
05-09 13:27:00.792  2319  2319 E Xposed  : 	at java.lang.Runtime.load0(Runtime.java:928)
05-09 13:27:00.792  2319  2319 E Xposed  : 	at java.lang.System.load(System.java:1621)
05-09 13:27:00.792  2319  2319 E Xposed  : 	at com.wrbug.dumpdex.Native.<clinit>(Native.java:20)
05-09 13:27:00.792  2319  2319 E Xposed  : 	at com.wrbug.dumpdex.Native.dump(Native Method)
05-09 13:27:00.792  2319  2319 E Xposed  : 	at com.wrbug.dumpdex.dump.OreoDump.init(OreoDump.java:32)
05-09 13:27:00.792  2319  2319 E Xposed  : 	at com.wrbug.dumpdex.XposedInit.handleLoadPackage(XposedInit.java:51)
05-09 13:27:00.792  2319  2319 E Xposed  : 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
05-09 13:27:00.792  2319  2319 E Xposed  : 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
05-09 13:27:00.792  2319  2319 E Xposed  : 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
05-09 13:27:00.792  2319  2319 E Xposed  : 	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
05-09 13:27:00.792  2319  2319 E Xposed  : 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
05-09 13:27:00.792  2319  2319 E Xposed  : 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
05-09 13:27:00.792  2319  2319 E Xposed  : 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
05-09 13:27:00.792  2319  2319 E Xposed  : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
05-09 13:27:00.792  2319  2319 E Xposed  : 	at android.os.Handler.dispatchMessage(Handler.java:105)
05-09 13:27:00.792  2319  2319 E Xposed  : 	at android.os.Looper.loop(Looper.java:164)
05-09 13:27:00.792  2319  2319 E Xposed  : 	at android.app.ActivityThread.main(ActivityThread.java:6541)
05-09 13:27:00.792  2319  2319 E Xposed  : 	at java.lang.reflect.Method.invoke(Native Method)
05-09 13:27:00.792  2319  2319 E Xposed  : 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
05-09 13:27:00.792  2319  2319 E Xposed  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
05-09 13:27:00.792  2319  2319 E Xposed  : 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

**Comment by Herbert77** [comment]
可以尝试这个方法。 https://copyprogramming.com/howto/arm-translation-on-genymotion

**Comment by Herbert77** [comment]
根据我自己的经验，就是 创建的 Emulator 的API 版本和 Genymotion-ARM-Translation 的版本要对应上。

**Comment by Herbert77** [comment]
根据我自己的经验，就是 创建的 Emulator 的API 版本和 Genymotion-ARM-Translation 的版本要对应上。
