### ISSUE TITLE
小米mix2 8.0系统 无法脱壳，好像是加载so文件失败，求发编译好的so文件

### ISSUE THREAD

**Issue by jason1235** [WrBug/dumpDex#24]
05-15 09:02:57.875 I/Xposed  ( 5068): dumpdex.PackerInfo-> find class:com.stub.StubApp
05-15 09:02:57.876 I/Xposed  ( 5068): dumpdex.PackerInfo-> find packerType :360加固
05-15 09:02:57.877 I/Xposed  ( 5068): dumpdex-> sdk version:26
05-15 09:02:57.879 E/Xposed  ( 5068): java.lang.UnsatisfiedLinkError: dlopen failed: "/data/local/tmp/libnativeDump64.so" is 64-bit instead of 32-bit
05-15 09:02:57.879 E/Xposed  ( 5068): 	at java.lang.Runtime.load0(Runtime.java:928)
05-15 09:02:57.879 E/Xposed  ( 5068): 	at java.lang.System.load(System.java:1621)
05-15 09:02:57.879 E/Xposed  ( 5068): 	at com.wrbug.dumpdex.Native.<clinit>(Native.java:20)
05-15 09:02:57.879 E/Xposed  ( 5068): 	at com.wrbug.dumpdex.Native.dump(Native Method)
05-15 09:02:57.879 E/Xposed  ( 5068): 	at com.wrbug.dumpdex.dump.OreoDump.init(OreoDump.java:32)
05-15 09:02:57.879 E/Xposed  ( 5068): 	at com.wrbug.dumpdex.XposedInit.handleLoadPackage(XposedInit.java:51)
05-15 09:02:57.879 E/Xposed  ( 5068): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
05-15 09:02:57.879 E/Xposed  ( 5068): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
05-15 09:02:57.879 E/Xposed  ( 5068): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
05-15 09:02:57.879 E/Xposed  ( 5068): 	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
05-15 09:02:57.879 E/Xposed  ( 5068): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
05-15 09:02:57.879 E/Xposed  ( 5068): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
05-15 09:02:57.879 E/Xposed  ( 5068): 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
05-15 09:02:57.879 E/Xposed  ( 5068): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1689)
05-15 09:02:57.879 E/Xposed  ( 5068): 	at android.os.Handler.dispatchMessage(Handler.java:105)
05-15 09:02:57.879 E/Xposed  ( 5068): 	at android.os.Looper.loop(Looper.java:171)
05-15 09:02:57.879 E/Xposed  ( 5068): 	at android.app.ActivityThread.main(ActivityThread.java:6684)
05-15 09:02:57.879 E/Xposed  ( 5068): 	at java.lang.reflect.Method.invoke(Native Method)
05-15 09:02:57.879 E/Xposed  ( 5068): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
05-15 09:02:57.879 E/Xposed  ( 5068): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
05-15 09:02:57.879 E/Xposed  ( 5068): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

**Comment by huangliulin** [comment]
同样的问题，请问解决了吗
