### ISSUE TITLE
dlopen failed: couldn't map "/data/local/tmp/libnativeDump64.so" segment 1: Permission denied

### ISSUE THREAD

**Issue by zyzling** [WrBug/dumpDex#47]
@WrBug  你好。我把编译好的cmake\release\obj\arm64-v8a下面的so复制到/data/data/tmp下。装上Xposed插件，然后运行加固的应用。在日志中报如下错误：
```
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/local/tmp/libnativeDump64.so" is 64-bit instead of 32-bit
10-12 21:13:41.541 E/Xposed  (12280): 	at java.lang.Runtime.load(Runtime.java:344)
10-12 21:13:41.541 E/Xposed  (12280): 	at java.lang.System.load(System.java:1079)
10-12 21:13:41.541 E/Xposed  (12280): 	at com.wrbug.dumpdex.Native.<clinit>(Native.java:20)
10-12 21:13:41.541 E/Xposed  (12280): 	at com.wrbug.dumpdex.dump.LowSdkDump.init(LowSdkDump.java:33)
10-12 21:13:41.541 E/Xposed  (12280): 	at com.wrbug.dumpdex.XposedInit.handleLoadPackage(XposedInit.java:53)
10-12 21:13:41.541 E/Xposed  (12280): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
10-12 21:13:41.541 E/Xposed  (12280): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
10-12 21:13:41.541 E/Xposed  (12280): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
10-12 21:13:41.541 E/Xposed  (12280): 	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:116)
10-12 21:13:41.541 E/Xposed  (12280): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
10-12 21:13:41.541 E/Xposed  (12280): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
10-12 21:13:41.541 E/Xposed  (12280): 	at android.app.ActivityThread.access$1600(ActivityThread.java:165)
10-12 21:13:41.541 E/Xposed  (12280): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437)
10-12 21:13:41.541 E/Xposed  (12280): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-12 21:13:41.541 E/Xposed  (12280): 	at android.os.Looper.loop(Looper.java:150)
10-12 21:13:41.541 E/Xposed  (12280): 	at android.app.ActivityThread.main(ActivityThread.java:5621)
10-12 21:13:41.541 E/Xposed  (12280): 	at java.lang.reflect.Method.invoke(Native Method)
10-12 21:13:41.541 E/Xposed  (12280): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
10-12 21:13:41.541 E/Xposed  (12280): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
10-12 21:13:41.541 E/Xposed  (12280): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```
这个看了已有的issues。里面说复制cmake\release\obj\armeabi-v7a目录下的so。然后改成libnativeDump64.so，然后又报如下错误：
```
10-12 21:11:17.181 E/Xposed  (11782): java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/data/local/tmp/libnativeDump64.so" segment 1: Permission denied
10-12 21:11:17.181 E/Xposed  (11782): 	at java.lang.Runtime.load(Runtime.java:344)
10-12 21:11:17.181 E/Xposed  (11782): 	at java.lang.System.load(System.java:1079)
10-12 21:11:17.181 E/Xposed  (11782): 	at com.wrbug.dumpdex.Native.<clinit>(Native.java:20)
10-12 21:11:17.181 E/Xposed  (11782): 	at com.wrbug.dumpdex.dump.LowSdkDump.init(LowSdkDump.java:33)
10-12 21:11:17.181 E/Xposed  (11782): 	at com.wrbug.dumpdex.XposedInit.handleLoadPackage(XposedInit.java:53)
10-12 21:11:17.181 E/Xposed  (11782): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
10-12 21:11:17.181 E/Xposed  (11782): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
10-12 21:11:17.181 E/Xposed  (11782): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
10-12 21:11:17.181 E/Xposed  (11782): 	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:116)
10-12 21:11:17.181 E/Xposed  (11782): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
10-12 21:11:17.181 E/Xposed  (11782): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
10-12 21:11:17.181 E/Xposed  (11782): 	at android.app.ActivityThread.access$1600(ActivityThread.java:165)
10-12 21:11:17.181 E/Xposed  (11782): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437)
10-12 21:11:17.181 E/Xposed  (11782): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-12 21:11:17.181 E/Xposed  (11782): 	at android.os.Looper.loop(Looper.java:150)
10-12 21:11:17.181 E/Xposed  (11782): 	at android.app.ActivityThread.main(ActivityThread.java:5621)
10-12 21:11:17.181 E/Xposed  (11782): 	at java.lang.reflect.Method.invoke(Native Method)
10-12 21:11:17.181 E/Xposed  (11782): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
10-12 21:11:17.181 E/Xposed  (11782): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
10-12 21:11:17.181 E/Xposed  (11782): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```
求解答。360加固。多谢。

**Comment by zyzling** [comment]
华为手机。按照[https://github.com/WrBug/dumpDex/issues/40](#40) 这位@h080294 仁兄的方法解决了。感谢。我的步骤是：
```
1. adb shell
2. su
3. getenforce  这时候输出是Enforcing
4.setenforce 0
5.getenforce  这时候输出是Permissive 
```
就可以了。
