### ISSUE TITLE
小米3M成功脱壳  诺基亚X6失败

### ISSUE THREAD

**Issue by geekplus001** [WrBug/dumpDex#67]
错误日志如下：请问怎么解决

02-28 12:16:47.232 I/Xposed  (  675): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
02-28 12:16:47.540 I/Xposed  (  675): Loading modules from /data/app/com.wrbug.dumpdex-fQCMUBSGfVWrg6E8oUJ4xA==/base.apk
02-28 12:16:47.943 I/Xposed  (  675):   Loading class com.wrbug.dumpdex.XposedInit
02-28 12:17:33.987 I/Xposed  ( 5303): dumpdex.PackerInfo-> find class:com.stub.StubApp
02-28 12:17:33.987 I/Xposed  ( 5303): dumpdex.PackerInfo-> find packerType :360加固
02-28 12:17:33.988 I/Xposed  ( 5303): dumpdex-> sdk version:27
02-28 12:17:34.001 E/Xposed  ( 5303): java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/local/tmp/libnativeDump64.so" not found
02-28 12:17:34.001 E/Xposed  ( 5303): 	at java.lang.Runtime.load0(Runtime.java:928)
02-28 12:17:34.001 E/Xposed  ( 5303): 	at java.lang.System.load(System.java:1621)
02-28 12:17:34.001 E/Xposed  ( 5303): 	at com.wrbug.dumpdex.Native.<clinit>(Native.java:20)
02-28 12:17:34.001 E/Xposed  ( 5303): 	at com.wrbug.dumpdex.Native.dump(Native Method)
02-28 12:17:34.001 E/Xposed  ( 5303): 	at com.wrbug.dumpdex.dump.OreoDump.init(OreoDump.java:32)
02-28 12:17:34.001 E/Xposed  ( 5303): 	at com.wrbug.dumpdex.XposedInit.handleLoadPackage(XposedInit.java:51)
02-28 12:17:34.001 E/Xposed  ( 5303): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
02-28 12:17:34.001 E/Xposed  ( 5303): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
02-28 12:17:34.001 E/Xposed  ( 5303): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
02-28 12:17:34.001 E/Xposed  ( 5303): 	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
02-28 12:17:34.001 E/Xposed  ( 5303): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
02-28 12:17:34.001 E/Xposed  ( 5303): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
02-28 12:17:34.001 E/Xposed  ( 5303): 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
02-28 12:17:34.001 E/Xposed  ( 5303): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1658)
02-28 12:17:34.001 E/Xposed  ( 5303): 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-28 12:17:34.001 E/Xposed  ( 5303): 	at android.os.Looper.loop(Looper.java:164)
02-28 12:17:34.001 E/Xposed  ( 5303): 	at android.app.ActivityThread.main(ActivityThread.java:6526)
02-28 12:17:34.001 E/Xposed  ( 5303): 	at java.lang.reflect.Method.invoke(Native Method)
02-28 12:17:34.001 E/Xposed  ( 5303): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
02-28 12:17:34.001 E/Xposed  ( 5303): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
02-28 12:17:34.001 E/Xposed  ( 5303): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

**Comment by FreeFlash** [comment]
看下cpu是什么架构的

**Comment by geekplus001** [comment]
诺基亚X6：







米3





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"FreeFlash"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月4日(星期四) 晚上6:54
收件人:&nbsp;"WrBug/dumpDex"<dumpDex@noreply.github.com&gt;;
抄送:&nbsp;"孟亚彬"<877048930@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [WrBug/dumpDex] 小米3M成功脱壳  诺基亚X6失败 (#67)





 
看下cpu是什么架构的
