### ISSUE TITLE
脱壳报错

### ISSUE THREAD

**Issue by voila1106** [WrBug/dumpDex#91]
[ 2022-12-23T23:30:48.655    10521: 14181: 14181 I/LSPosed-Bridge  ] Loading module com.wrbug.dumpdex from /data/app/~~NpJMz3N-thMFAE6tn4G8lw==/com.wrbug.dumpdex-isAKl4ZT3rll5MNubEw9Sg==/base.apk
[ 2022-12-23T23:30:48.665    10521: 14181: 14181 I/LSPosed-Bridge  ]   Loading class com.wrbug.dumpdex.XposedInit
[ 2022-12-23T23:30:48.706    10521: 14181: 14181 I/LSPosed-Bridge  ] dumpdex.PackerInfo-> find class:com.stub.StubApp
[ 2022-12-23T23:30:48.706    10521: 14181: 14181 I/LSPosed-Bridge  ] dumpdex.PackerInfo-> find packerType :360加固
[ 2022-12-23T23:30:48.706    10521: 14181: 14181 I/LSPosed-Bridge  ] dumpdex-> sdk version:31
[ 2022-12-23T23:30:48.707    10521: 14181: 14181 I/LSPosed-Bridge  ] dumpdex.LowSdkDump-> start hook Instrumentation#newApplication
[ 2022-12-23T23:30:48.868    10521: 14181: 14181 I/LSPosed-Bridge  ] dumpdex.LowSdkDump-> Application=com.stub.StubApp@6872824
[ 2022-12-23T23:30:48.868    10521: 14181: 14181 I/LSPosed-Bridge  ] dumpdex.LowSdkDump-> decCache=java.lang.DexCache@59f3f8d
[ 2022-12-23T23:30:48.868    10521: 14181: 14181 E/LSPosed-Bridge  ] java.lang.NoSuchMethodError: java.lang.DexCache#getDex()#bestmatch
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(Unknown Source:4)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(Unknown Source:4)
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:4)
	at com.wrbug.dumpdex.dump.LowSdkDump.dump(LowSdkDump.java:51)
	at com.wrbug.dumpdex.dump.LowSdkDump.access$000(LowSdkDump.java:24)
	at com.wrbug.dumpdex.dump.LowSdkDump$1.afterHookedMethod(LowSdkDump.java:42)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.newApplication(Unknown Source:17)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1369)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7044)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1600(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2129)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8283)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by voila1106** [comment]
手机是安卓12  app的targetsdk是25  我猜是这里的问题

**Comment by 2054686334** [comment]
同样脱壳360加固报错NoSuchMethodError
